
name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |-
        echo "\nUpdate readme `date`" >> README.md
    - name: Commit and push if changed
      run: |-
        git add README.md
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
